# Generated by Django 5.2.1 on 2025-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbImoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quarto', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_imoveis',
                'managed': True,
            },
        ),
    ]
